@echo off
echo 🔧 MegaMelange 포트 설정 스크립트
echo ================================
echo.
echo 현재 포트 설정을 변경하거나 .env 파일을 생성합니다.
echo.

REM Load existing environment variables from .env file if it exists
if exist "../.env" (
    echo 📄 기존 .env 파일을 읽는 중...
    for /f "usebackq tokens=1,2 delims==" %%a in ("../.env") do (
        if not "%%a"=="" if not "%%b"=="" (
            set "%%a=%%b"
        )
    )
    echo ✅ 기존 설정 로드 완료
    echo.
)

REM Set current values or defaults
if not defined UNREAL_TCP_PORT set UNREAL_TCP_PORT=55557
if not defined UNREAL_TCP_HOST set UNREAL_TCP_HOST=127.0.0.1
if not defined HTTP_BRIDGE_PORT set HTTP_BRIDGE_PORT=8080
if not defined FRONTEND_PORT set FRONTEND_PORT=3000

echo 📋 현재 포트 설정:
echo    🔌 Unreal TCP 포트: %UNREAL_TCP_PORT%
echo    🌉 HTTP Bridge 포트: %HTTP_BRIDGE_PORT%
echo    🌐 Frontend 포트: %FRONTEND_PORT%
echo    🖥️  Host: %UNREAL_TCP_HOST%
echo.

echo 🎯 포트 설정 옵션:
echo    1) 모든 포트를 기본값으로 설정 (55557, 8080, 3000)
echo    2) 포트 충돌 방지용 대체 포트 설정 (55558, 8081, 3001)
echo    3) 수동으로 각 포트 설정
echo    4) 현재 설정 유지하고 .env 파일만 생성/업데이트
echo    5) .env 파일 삭제하고 기본값으로 되돌리기
echo    6) 종료
echo.

set /p choice=선택하세요 (1-6): 

if "%choice%"=="1" goto set_default
if "%choice%"=="2" goto set_alternative
if "%choice%"=="3" goto set_manual
if "%choice%"=="4" goto write_env
if "%choice%"=="5" goto delete_env
if "%choice%"=="6" goto end

echo ❌ 잘못된 선택입니다.
pause
goto :eof

:set_default
echo.
echo 🔄 기본 포트로 설정 중...
set UNREAL_TCP_PORT=55557
set UNREAL_TCP_HOST=127.0.0.1
set HTTP_BRIDGE_PORT=8080
set FRONTEND_PORT=3000
goto write_env

:set_alternative
echo.
echo 🔄 대체 포트로 설정 중...
set UNREAL_TCP_PORT=55558
set UNREAL_TCP_HOST=127.0.0.1
set HTTP_BRIDGE_PORT=8081
set FRONTEND_PORT=3001
goto write_env

:set_manual
echo.
echo 🖊️  수동 포트 설정:
echo.

set /p new_tcp_port=Unreal TCP 포트 (현재: %UNREAL_TCP_PORT%): 
if not "%new_tcp_port%"=="" set UNREAL_TCP_PORT=%new_tcp_port%

set /p new_bridge_port=HTTP Bridge 포트 (현재: %HTTP_BRIDGE_PORT%): 
if not "%new_bridge_port%"=="" set HTTP_BRIDGE_PORT=%new_bridge_port%

set /p new_frontend_port=Frontend 포트 (현재: %FRONTEND_PORT%): 
if not "%new_frontend_port%"=="" set FRONTEND_PORT=%new_frontend_port%

set /p new_host=Host 주소 (현재: %UNREAL_TCP_HOST%): 
if not "%new_host%"=="" set UNREAL_TCP_HOST=%new_host%

goto write_env

:write_env
echo.
echo 💾 .env 파일 생성 중...

REM Create main .env file
(
echo # MegaMelange Port Configuration
echo # Generated by script-set-ports.bat on %date% %time%
echo.
echo # Unreal Engine TCP Server Port
echo UNREAL_TCP_PORT=%UNREAL_TCP_PORT%
echo UNREAL_TCP_HOST=%UNREAL_TCP_HOST%
echo.
echo # HTTP Bridge Port
echo HTTP_BRIDGE_PORT=%HTTP_BRIDGE_PORT%
echo.
echo # Frontend Port ^(used by npm run dev^)
echo FRONTEND_PORT=%FRONTEND_PORT%
) > ../.env

echo ✅ .env 파일 생성 완료

REM Create Frontend .env.local file
echo.
echo 💾 Frontend/.env.local 파일 생성 중...

if not exist "../Frontend" (
    echo ⚠️  Frontend 폴더가 없습니다. Frontend/.env.local 건너뜀.
) else (
    (
    echo # Frontend Environment Variables
    echo # Generated by script-set-ports.bat on %date% %time%
    echo.
    echo # HTTP Bridge Port - must match the port used by Python HTTP bridge
    echo NEXT_PUBLIC_HTTP_BRIDGE_PORT=%HTTP_BRIDGE_PORT%
    echo.
    echo # OpenAI API Key ^(required for web interface^)
    echo # OPENAI_API_KEY=your_openai_api_key_here
    ) > ../Frontend\.env.local
    
    echo ✅ Frontend/.env.local 파일 생성 완료
)

echo.
echo 🎉 포트 설정 완료!
echo.
echo 📋 설정된 포트:
echo    🔌 Unreal TCP: %UNREAL_TCP_PORT%
echo    🌉 HTTP Bridge: %HTTP_BRIDGE_PORT%
echo    🌐 Frontend: %FRONTEND_PORT%
echo    🖥️  Host: %UNREAL_TCP_HOST%
echo.
echo 💡 이제 script-init-ports.bat를 실행하여 서비스를 시작할 수 있습니다.
echo.
pause
goto :eof

:delete_env
echo.
echo ⚠️  경고: .env 파일을 삭제하면 모든 설정이 기본값으로 되돌아갑니다.
set /p confirm=정말 삭제하시겠습니까? (y/N): 

if /i "%confirm%"=="y" (
    if exist "../.env" (
        del "../.env"
        echo ✅ .env 파일이 삭제되었습니다.
    ) else (
        echo ℹ️  .env 파일이 존재하지 않습니다.
    )
    
    if exist "../Frontend\.env.local" (
        del "../Frontend\.env.local"
        echo ✅ Frontend/.env.local 파일이 삭제되었습니다.
    ) else (
        echo ℹ️  Frontend/.env.local 파일이 존재하지 않습니다.
    )
    echo.
    echo 🔄 기본 포트 설정으로 되돌아갔습니다.
) else (
    echo ❌ 삭제가 취소되었습니다.
)
echo.
pause
goto :eof

:end
echo.
echo 👋 스크립트를 종료합니다.
pause